---
- hosts: localhost
  tasks:
    - name: Make sure that Winericks does not fail with any special checks first
      winetricks:
        args: "--version"
      changed_when: False
      register: winetricks_module_output

    - name: Test the "winetricks" Ansible module by verifying the Winetricks version
      fail:
        msg: This is not a valid Winetricks output for the version information
      when: "'- sha256sum: ' not in winetricks_module_output.stdout"

    - name: View the Winetricks module output
      debug:
        var: winetricks_module_output
